volumes:
  data:

services:
  myapp:
    image: chloe1997discordserver:latest
    environment:
      - DATABASE_URL=postgres://postgres:postgrespw@postgres:5432
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
